### ISSUE TITLE
Webpack hangs when recompiling (using HMR).

### ISSUE THREAD

**Issue by henrikericsson** [jlowgren/esi-webpack-plugin#2]
Everything runs/recompiles as expected when i remove EsiWebpackPlugin.

![part_of_config](https://user-images.githubusercontent.com/35683499/36030803-e13fc9de-0da8-11e8-94b3-a3387fcba838.PNG)

**Comment by jlowgren** [comment]
Can you provide a minimal project that reproduces this issue?

**Comment by jlowgren** [comment]
I'm going to assume this has been resolved due to the lack of response.
